/* Generated by Cython 0.9.8 on Sun Jun 15 10:29:00 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   ((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,

  typedef struct {
       void *buf;
       Py_ssize_t len;
       int readonly;
       const char *format;
       int ndim;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       Py_ssize_t itemsize;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)
#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__pyhurd__hurd
#include "gnu_source.h"
#include "stdlib.h"
#include "hurd/hurd_types.h"
#include "hurd.h"
#include "hurd/io.h"
#include "mach/port.h"
#include "mach/message.h"
#include "mach/mach_traps.h"
#include "mach/mach_types.h"
#include "mach/error.h"
#include "mach.h"
#include "mach/machine/vm_types.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static char __pyx_mdoc[] = "\nPyHurd - A pytonish GNU/Hurd\n";

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(char *name); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

/* Type declarations */

/* "/home/jimcrow/pyhurd/pyhurd/pyhurd.mach.pxd":33
 *     ctypedef unsigned int natural_t
 * 
 * cdef class MachPort:             # <<<<<<<<<<<<<<
 *      cdef readonly mach_port_t mach_port
 */

struct __pyx_obj_6pyhurd_4mach_MachPort {
  PyObject_HEAD
  mach_port_t mach_port;
};

/* "/home/jimcrow/pyhurd/pyhurd/pyhurd.hurd.pxd":24
 * from pyhurd.mach cimport MachPort
 * 
 * cdef class IO (MachPort):             # <<<<<<<<<<<<<<
 *     cdef readonly io_t io_object
 * 
 */

struct __pyx_obj_6pyhurd_4hurd_IO {
  struct __pyx_obj_6pyhurd_4mach_MachPort __pyx_base;
  io_t io_object;
};
/* Module declarations from pyhurd.mach */

static PyTypeObject *__pyx_ptype_6pyhurd_4mach_MachPort = 0;
/* Module declarations from pyhurd.hurd */

static PyTypeObject *__pyx_ptype_6pyhurd_4hurd_IO = 0;


/* Implementation of pyhurd.hurd */


static PyObject *__pyx_int_0;

static char __pyx_k___str__[] = "__str__";
static char __pyx_k_readable[] = "readable";
static char __pyx_k_read[] = "read";
static char __pyx_k_write[] = "write";
static char __pyx_k_seek[] = "seek";
static char __pyx_k_set_all_openmodes[] = "set_all_openmodes";
static char __pyx_k_get_openmodes[] = "get_openmodes";
static char __pyx_k_set_some_openmodes[] = "set_some_openmodes";
static char __pyx_k_1[] = "clear_some_openmodes";
static char __pyx_k_async[] = "async";
static char __pyx_k_mod_owner[] = "mod_owner";
static char __pyx_k_get_owner[] = "get_owner";
static char __pyx_k_select[] = "select";

static PyObject *__pyx_kp___str__;
static PyObject *__pyx_kp_readable;
static PyObject *__pyx_kp_read;
static PyObject *__pyx_kp_write;
static PyObject *__pyx_kp_seek;
static PyObject *__pyx_kp_set_all_openmodes;
static PyObject *__pyx_kp_get_openmodes;
static PyObject *__pyx_kp_set_some_openmodes;
static PyObject *__pyx_kp_1;
static PyObject *__pyx_kp_async;
static PyObject *__pyx_kp_mod_owner;
static PyObject *__pyx_kp_get_owner;
static PyObject *__pyx_kp_select;


/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":21
 * 
 * cdef class IO (MachPort):
 *     def __str__ (self):             # <<<<<<<<<<<<<<
 *         return 'IO: mach port: %s' % self.mach_port
 * 
 */

static PyObject *__pyx_kp_2;

static char __pyx_k_2[] = "IO: mach port: %s";

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO___str__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO___str__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":22
 * cdef class IO (MachPort):
 *     def __str__ (self):
 *         return 'IO: mach port: %s' % self.mach_port             # <<<<<<<<<<<<<<
 * 
 *     def readable (self):
 */
  __pyx_1 = PyLong_FromUnsignedLong(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyNumber_Remainder(__pyx_kp_2, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.hurd.IO.__str__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":24
 *         return 'IO: mach port: %s' % self.mach_port
 * 
 *     def readable (self):             # <<<<<<<<<<<<<<
 *         """
 *         Checks if io object is readable and return avaiable amount
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_readable(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_readable[] = "\n        Checks if io object is readable and return avaiable amount\n        of data to read/write\n\n       Return:\n            tuple of error and amount integer values\n\n        Hurd definition:\n            kern_return_t io_readable (\n                io_t io_object,\n                vm_size_t *amount)\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_readable(PyObject *__pyx_v_self, PyObject *unused) {
  vm_size_t __pyx_v_amount;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":38
 *         """
 * 
 *         cdef vm_size_t amount = 0             # <<<<<<<<<<<<<<
 *         error = io_readable(self.mach_port, &amount)
 * 
 */
  __pyx_v_amount = 0;


  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":39
 * 
 *         cdef vm_size_t amount = 0
 *         error = io_readable(self.mach_port, &amount)             # <<<<<<<<<<<<<<
 * 
 *         return error, amount
 */
  __pyx_1 = PyInt_FromLong(io_readable(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, (&__pyx_v_amount))); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":41
 *         error = io_readable(self.mach_port, &amount)
 * 
 *         return error, amount             # <<<<<<<<<<<<<<
 * 
 *     def read (self, amount, offset = 0):
 */
  __pyx_1 = PyLong_FromUnsignedLong(__pyx_v_amount); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_r = ((PyObject *)__pyx_2);
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.hurd.IO.readable");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":43
 *         return error, amount
 * 
 *     def read (self, amount, offset = 0):             # <<<<<<<<<<<<<<
 *         """
 *         Reads data from io object.
 */

static PyObject *__pyx_int_1;

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_read[] = "\n        Reads data from io object.\n\n        Parameters:\n            offset\n            amount\n\n        Returns:\n            tuple of error (integer) and data (string)\n            None - if nothing to read\n\n        Hurd definition:\n            kern_return_t io_read (\n                io_t io_object,\n                data_t *data,\n                mach_msg_type_number_t *dataCnt,\n                loff_t offset,\n                vm_size_t amount)\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_amount = 0;
  PyObject *__pyx_v_offset = 0;
  vm_size_t __pyx_v_read_amount;
  data_t __pyx_v_data;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  size_t __pyx_2;
  loff_t __pyx_3;
  vm_size_t __pyx_4;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"amount","offset",0};
  __pyx_v_offset = __pyx_int_0;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    __pyx_v_amount = PyTuple_GET_ITEM(__pyx_args, 0);
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_offset = PyTuple_GET_ITEM(__pyx_args, 1);
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_amount, &__pyx_v_offset))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("pyhurd.hurd.IO.read");
  return NULL;
  __pyx_L3:;
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":65
 * 
 *         cdef vm_size_t read_amount
 *         cdef data_t data = <data_t>malloc(amount + 1)             # <<<<<<<<<<<<<<
 *         error = io_read(self.mach_port, &data, &read_amount, offset, amount)
 * 
 */
  __pyx_1 = PyNumber_Add(__pyx_v_amount, __pyx_int_1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyInt_AsUnsignedLongMask(__pyx_1); if (unlikely((__pyx_2 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_data = ((char *)malloc(__pyx_2));


  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":66
 *         cdef vm_size_t read_amount
 *         cdef data_t data = <data_t>malloc(amount + 1)
 *         error = io_read(self.mach_port, &data, &read_amount, offset, amount)             # <<<<<<<<<<<<<<
 * 
 *         if read_amount == 0:
 */
  __pyx_3 = __pyx_PyInt_long(__pyx_v_offset); if (unlikely((__pyx_3 == (long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyInt_AsUnsignedLongMask(__pyx_v_amount); if (unlikely((__pyx_4 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(io_read(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, (&__pyx_v_data), (&__pyx_v_read_amount), __pyx_3, __pyx_4)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":68
 *         error = io_read(self.mach_port, &data, &read_amount, offset, amount)
 * 
 *         if read_amount == 0:             # <<<<<<<<<<<<<<
 *             return None
 * 
 */
  __pyx_5 = (__pyx_v_read_amount == 0);
  if (__pyx_5) {

    /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":69
 * 
 *         if read_amount == 0:
 *             return None             # <<<<<<<<<<<<<<
 * 
 *         data[read_amount] = c'\0'
 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":71
 *             return None
 * 
 *         data[read_amount] = c'\0'             # <<<<<<<<<<<<<<
 *         return error, data
 * 
 */
  (__pyx_v_data[__pyx_v_read_amount]) = '\0';

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":72
 * 
 *         data[read_amount] = c'\0'
 *         return error, data             # <<<<<<<<<<<<<<
 * 
 *     def write (self, data, offset = 0):
 */
  __pyx_1 = __Pyx_PyBytes_FromString(__pyx_v_data); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(2); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_r = ((PyObject *)__pyx_6);
  __pyx_6 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("pyhurd.hurd.IO.read");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":74
 *         return error, data
 * 
 *     def write (self, data, offset = 0):             # <<<<<<<<<<<<<<
 *         """
 *         Writes data to io object.
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_write(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_write[] = "\n        Writes data to io object.\n\n        Parameters:\n            data - string to write\n            offset\n\n        Returns:\n          tuple of error and amount values\n\n        Hurd definition:\n            kern_return_t io_write (\n                io_t io_object,\n	        data_t data,\n	        mach_msg_type_number,\n	        loff_t offset,\n	        vm_size_t *amount)\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_write(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  PyObject *__pyx_v_offset = 0;
  vm_size_t __pyx_v_write_amount;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  data_t __pyx_1;
  Py_ssize_t __pyx_2 = 0;
  loff_t __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"data","offset",0};
  __pyx_v_offset = __pyx_int_0;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    __pyx_v_data = PyTuple_GET_ITEM(__pyx_args, 0);
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_offset = PyTuple_GET_ITEM(__pyx_args, 1);
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_data, &__pyx_v_offset))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("pyhurd.hurd.IO.write");
  return NULL;
  __pyx_L3:;
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":95
 * 
 *         cdef vm_size_t write_amount
 *         error = io_write(self.mach_port, data, len(data), offset, &write_amount)             # <<<<<<<<<<<<<<
 *         return error, write_amount
 * 
 */
  __pyx_1 = __Pyx_PyBytes_AsString(__pyx_v_data); if (unlikely((!__pyx_1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyObject_Length(__pyx_v_data); if (unlikely(__pyx_2 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = __pyx_PyInt_long(__pyx_v_offset); if (unlikely((__pyx_3 == (long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(io_write(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, __pyx_1, __pyx_2, __pyx_3, (&__pyx_v_write_amount))); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_4;
  __pyx_4 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":96
 *         cdef vm_size_t write_amount
 *         error = io_write(self.mach_port, data, len(data), offset, &write_amount)
 *         return error, write_amount             # <<<<<<<<<<<<<<
 * 
 *     def seek (self, offset, whence):
 */
  __pyx_4 = PyLong_FromUnsignedLong(__pyx_v_write_amount); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
  __pyx_4 = 0;
  __pyx_r = ((PyObject *)__pyx_5);
  __pyx_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("pyhurd.hurd.IO.write");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":98
 *         return error, write_amount
 * 
 *     def seek (self, offset, whence):             # <<<<<<<<<<<<<<
 *         """
 *         Change current read/write offset
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_seek(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_seek[] = "\n        Change current read/write offset\n\n        Return:\n            tuple of error and new position\n\n        Hurd definition:\n            kern_return_t io_seek (\n                io_t io_object,\n                loff_t offset,\n                int whence,\n                loff_t * newp)\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_seek(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_offset = 0;
  PyObject *__pyx_v_whence = 0;
  loff_t __pyx_v_new_position;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  loff_t __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"offset","whence",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_offset = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_whence = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_offset, &__pyx_v_whence))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("pyhurd.hurd.IO.seek");
  return NULL;
  __pyx_L3:;
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":114
 * 
 *         cdef loff_t new_position
 *         error = io_seek(self.mach_port, offset, whence, &new_position)             # <<<<<<<<<<<<<<
 *         return error, new_position
 * 
 */
  __pyx_1 = __pyx_PyInt_long(__pyx_v_offset); if (unlikely((__pyx_1 == (long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_whence); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(io_seek(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, __pyx_1, __pyx_2, (&__pyx_v_new_position))); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_3;
  __pyx_3 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":115
 *         cdef loff_t new_position
 *         error = io_seek(self.mach_port, offset, whence, &new_position)
 *         return error, new_position             # <<<<<<<<<<<<<<
 * 
 *     def set_all_openmodes (self, int newbits):
 */
  __pyx_3 = PyInt_FromLong(__pyx_v_new_position); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_3 = 0;
  __pyx_r = ((PyObject *)__pyx_4);
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pyhurd.hurd.IO.seek");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":117
 *         return error, new_position
 * 
 *     def set_all_openmodes (self, int newbits):             # <<<<<<<<<<<<<<
 *         """
 *         Return:
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_set_all_openmodes(PyObject *__pyx_v_self, PyObject *__pyx_arg_newbits); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_set_all_openmodes[] = "\n        Return:\n             error\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_set_all_openmodes(PyObject *__pyx_v_self, PyObject *__pyx_arg_newbits) {
  int __pyx_v_newbits;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  assert(__pyx_arg_newbits); {
    __pyx_v_newbits = __pyx_PyInt_int(__pyx_arg_newbits); if (unlikely((__pyx_v_newbits == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("pyhurd.hurd.IO.set_all_openmodes");
  return NULL;
  __pyx_L3:;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":122
 *              error
 *         """
 *         return io_set_all_openmodes(self.mach_port, newbits)             # <<<<<<<<<<<<<<
 * 
 *     def get_openmodes (self):
 */
  __pyx_1 = PyInt_FromLong(io_set_all_openmodes(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, __pyx_v_newbits)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pyhurd.hurd.IO.set_all_openmodes");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":124
 *         return io_set_all_openmodes(self.mach_port, newbits)
 * 
 *     def get_openmodes (self):             # <<<<<<<<<<<<<<
 *         """
 *         Return:
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_get_openmodes(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_get_openmodes[] = "\n        Return:\n             error, bits\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_get_openmodes(PyObject *__pyx_v_self, PyObject *unused) {
  int __pyx_v_bits;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":131
 * 
 *         cdef int bits
 *         error = io_get_openmodes(self.mach_port, &bits)             # <<<<<<<<<<<<<<
 *         return error, bits
 * 
 */
  __pyx_1 = PyInt_FromLong(io_get_openmodes(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, (&__pyx_v_bits))); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 131; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":132
 *         cdef int bits
 *         error = io_get_openmodes(self.mach_port, &bits)
 *         return error, bits             # <<<<<<<<<<<<<<
 * 
 *     def set_some_openmodes (self, bits_to_set):
 */
  __pyx_1 = PyInt_FromLong(__pyx_v_bits); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 132; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_r = ((PyObject *)__pyx_2);
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.hurd.IO.get_openmodes");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":134
 *         return error, bits
 * 
 *     def set_some_openmodes (self, bits_to_set):             # <<<<<<<<<<<<<<
 *         """
 *         Return:
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_set_some_openmodes(PyObject *__pyx_v_self, PyObject *__pyx_v_bits_to_set); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_set_some_openmodes[] = "\n        Return:\n             error\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_set_some_openmodes(PyObject *__pyx_v_self, PyObject *__pyx_v_bits_to_set) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":140
 *         """
 * 
 *         return io_set_some_openmodes(self.mach_port, bits_to_set)             # <<<<<<<<<<<<<<
 * 
 *     def clear_some_openmodes (self, bits_to_clear):
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_bits_to_set); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(io_set_some_openmodes(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, __pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.hurd.IO.set_some_openmodes");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":142
 *         return io_set_some_openmodes(self.mach_port, bits_to_set)
 * 
 *     def clear_some_openmodes (self, bits_to_clear):             # <<<<<<<<<<<<<<
 *         """
 *         Return:
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_clear_some_openmodes(PyObject *__pyx_v_self, PyObject *__pyx_v_bits_to_clear); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_clear_some_openmodes[] = "\n        Return:\n             error\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_clear_some_openmodes(PyObject *__pyx_v_self, PyObject *__pyx_v_bits_to_clear) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":148
 *         """
 * 
 *         return io_clear_some_openmodes(self.mach_port, bits_to_clear)             # <<<<<<<<<<<<<<
 * 
 *     def async (self, notify_port, notify_portPoly):
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_bits_to_clear); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(io_clear_some_openmodes(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, __pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 148; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.hurd.IO.clear_some_openmodes");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":150
 *         return io_clear_some_openmodes(self.mach_port, bits_to_clear)
 * 
 *     def async (self, notify_port, notify_portPoly):             # <<<<<<<<<<<<<<
 *         """
 *         This requests that the IO object send SIGIO and SIGURG signals,
 */

static char __pyx_k_mach_port[] = "mach_port";

static PyObject *__pyx_kp_mach_port;

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_async(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_async[] = "\n        This requests that the IO object send SIGIO and SIGURG signals,\n        when appropriate, to the designated port using sig_post.  A\n        port is also returned which will be used as the reference port in\n        sending such signals (this is the \"async IO ID\" port).  The async\n        call is cancelled by deleting all refernces to the async_id_port.\n        Each call to io_async generates a new ASYNC_ID_PORT.\n\n        Return:\n             error, async_id_port\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_async(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_notify_port = 0;
  PyObject *__pyx_v_notify_portPoly = 0;
  mach_port_t __pyx_v__async_id_port;
  PyObject *__pyx_v_error;
  PyObject *__pyx_v_async_id_port;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  mach_port_t __pyx_2;
  mach_msg_type_name_t __pyx_3;
  static char *__pyx_argnames[] = {"notify_port","notify_portPoly",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_notify_port = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_notify_portPoly = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_notify_port, &__pyx_v_notify_portPoly))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 150; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("pyhurd.hurd.IO.async");
  return NULL;
  __pyx_L3:;
  __pyx_v_error = Py_None; Py_INCREF(Py_None);
  __pyx_v_async_id_port = Py_None; Py_INCREF(Py_None);

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":164
 * 
 *         cdef mach_port_t _async_id_port
 *         error = io_async(self.mach_port, notify_port.mach_port, notify_portPoly, &_async_id_port)             # <<<<<<<<<<<<<<
 * 
 *         async_id_port = MachPort()
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_notify_port, __pyx_kp_mach_port); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyInt_AsUnsignedLongMask(__pyx_1); if (unlikely((__pyx_2 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_3 = PyInt_AsUnsignedLongMask(__pyx_v_notify_portPoly); if (unlikely((__pyx_3 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(io_async(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, __pyx_2, __pyx_3, (&__pyx_v__async_id_port))); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 164; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":166
 *         error = io_async(self.mach_port, notify_port.mach_port, notify_portPoly, &_async_id_port)
 * 
 *         async_id_port = MachPort()             # <<<<<<<<<<<<<<
 *         async_id_port.mach_port = _async_id_port
 * 
 */
  __pyx_1 = PyObject_Call(((PyObject*)__pyx_ptype_6pyhurd_4mach_MachPort), ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 166; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_async_id_port);
  __pyx_v_async_id_port = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":167
 * 
 *         async_id_port = MachPort()
 *         async_id_port.mach_port = _async_id_port             # <<<<<<<<<<<<<<
 * 
 *         return error, async_id_port
 */
  __pyx_1 = PyLong_FromUnsignedLong(__pyx_v__async_id_port); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_async_id_port, __pyx_kp_mach_port, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 167; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":169
 *         async_id_port.mach_port = _async_id_port
 * 
 *         return error, async_id_port             # <<<<<<<<<<<<<<
 * 
 *     def mod_owner (self, owner):
 */
  __pyx_1 = PyTuple_New(2); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 169; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_error);
  Py_INCREF(__pyx_v_async_id_port);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_async_id_port);
  __pyx_r = ((PyObject *)__pyx_1);
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pyhurd.hurd.IO.async");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  Py_DECREF(__pyx_v_async_id_port);
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":171
 *         return error, async_id_port
 * 
 *     def mod_owner (self, owner):             # <<<<<<<<<<<<<<
 *         """
 *         Set the owner of the IO object.  For terminals, this affects
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_mod_owner(PyObject *__pyx_v_self, PyObject *__pyx_v_owner); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_mod_owner[] = "\n        Set the owner of the IO object.  For terminals, this affects\n        controlling terminal behavior (see term_become_ctty).  For all\n        objects this affects old-style async IO.  Negative values represent\n        pgrps.  This has nothing to do with the owner of a file (as\n        returned by io_stat, and as used for various permission checks by\n        filesystems).  An owner of 0 indicates that there is no owner.\n\n        Return:\n             error\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_mod_owner(PyObject *__pyx_v_self, PyObject *__pyx_v_owner) {
  PyObject *__pyx_r;
  pid_t __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":184
 *         """
 * 
 *         return io_mod_owner(self.mach_port, owner)             # <<<<<<<<<<<<<<
 * 
 *     def get_owner (self):
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_owner); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 184; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(io_mod_owner(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, __pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 184; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.hurd.IO.mod_owner");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":186
 *         return io_mod_owner(self.mach_port, owner)
 * 
 *     def get_owner (self):             # <<<<<<<<<<<<<<
 *         """
 *         Get the owner of the IO object.  For terminals, this affects
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_get_owner(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_get_owner[] = "\n        Get the owner of the IO object.  For terminals, this affects\n        controlling terminal behavior (see term_become_ctty).  For all\n        objects this affects old-style async IO.  Negative values represent\n        pgrps.  This has nothing to do with the owner of a file (as\n        returned by io_stat, and as used for various permission checks by\n        filesystems).  An owner of 0 indicates that there is no owner.\n\n        Return:\n             error, owner\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_get_owner(PyObject *__pyx_v_self, PyObject *unused) {
  pid_t __pyx_v_owner;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":200
 * 
 *         cdef pid_t owner
 *         error = io_get_owner(self.mach_port, &owner)             # <<<<<<<<<<<<<<
 *         return error, owner
 * 
 */
  __pyx_1 = PyInt_FromLong(io_get_owner(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, (&__pyx_v_owner))); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 200; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_1;
  __pyx_1 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":201
 *         cdef pid_t owner
 *         error = io_get_owner(self.mach_port, &owner)
 *         return error, owner             # <<<<<<<<<<<<<<
 * 
 *     def select (self, reply, timeout, select_type):
 */
  __pyx_1 = PyInt_FromLong(__pyx_v_owner); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 201; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_r = ((PyObject *)__pyx_2);
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.hurd.IO.get_owner");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  return __pyx_r;
}

/* "/home/jimcrow/pyhurd/pyhurd/io.pyx":203
 *         return error, owner
 * 
 *     def select (self, reply, timeout, select_type):             # <<<<<<<<<<<<<<
 *         """
 *         SELECT_TYPE is the bitwise OR of SELECT_READ, SELECT_WRITE, and SELECT_URG.
 */

static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_select(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6pyhurd_4hurd_2IO_select[] = "\n        SELECT_TYPE is the bitwise OR of SELECT_READ, SELECT_WRITE, and SELECT_URG.\n        Block until one of the indicated types of i/o can be done \"quickly\", and\n        return the types that are then available.\n\n        Return:\n            error, select_type\n        ";
static PyObject *__pyx_pf_6pyhurd_4hurd_2IO_select(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_reply = 0;
  PyObject *__pyx_v_timeout = 0;
  PyObject *__pyx_v_select_type = 0;
  int __pyx_v__select_type;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  int __pyx_1;
  mach_port_t __pyx_2;
  natural_t __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"reply","timeout","select_type",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 3)) {
    __pyx_v_reply = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_timeout = PyTuple_GET_ITEM(__pyx_args, 1);
    __pyx_v_select_type = PyTuple_GET_ITEM(__pyx_args, 2);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_reply, &__pyx_v_timeout, &__pyx_v_select_type))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 203; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("pyhurd.hurd.IO.select");
  return NULL;
  __pyx_L3:;
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":213
 *         """
 * 
 *         cdef int _select_type = select_type             # <<<<<<<<<<<<<<
 *         error = io_select(self.mach_port, reply, timeout, &_select_type)
 *         return error, _select_type
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_select_type); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 213; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_v__select_type = __pyx_1;


  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":214
 * 
 *         cdef int _select_type = select_type
 *         error = io_select(self.mach_port, reply, timeout, &_select_type)             # <<<<<<<<<<<<<<
 *         return error, _select_type
 */
  __pyx_2 = PyInt_AsUnsignedLongMask(__pyx_v_reply); if (unlikely((__pyx_2 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = PyInt_AsUnsignedLongMask(__pyx_v_timeout); if (unlikely((__pyx_3 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(io_select(((struct __pyx_obj_6pyhurd_4hurd_IO *)__pyx_v_self)->__pyx_base.mach_port, __pyx_2, __pyx_3, (&__pyx_v__select_type))); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 214; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_4;
  __pyx_4 = 0;

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":215
 *         cdef int _select_type = select_type
 *         error = io_select(self.mach_port, reply, timeout, &_select_type)
 *         return error, _select_type             # <<<<<<<<<<<<<<
 */
  __pyx_4 = PyInt_FromLong(__pyx_v__select_type); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 215; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
  __pyx_4 = 0;
  __pyx_r = ((PyObject *)__pyx_5);
  __pyx_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("pyhurd.hurd.IO.select");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  return __pyx_r;
}

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp___str__, __pyx_k___str__, sizeof(__pyx_k___str__), 0, 1, 1},
  {&__pyx_kp_readable, __pyx_k_readable, sizeof(__pyx_k_readable), 0, 1, 1},
  {&__pyx_kp_read, __pyx_k_read, sizeof(__pyx_k_read), 0, 1, 1},
  {&__pyx_kp_write, __pyx_k_write, sizeof(__pyx_k_write), 0, 1, 1},
  {&__pyx_kp_seek, __pyx_k_seek, sizeof(__pyx_k_seek), 0, 1, 1},
  {&__pyx_kp_set_all_openmodes, __pyx_k_set_all_openmodes, sizeof(__pyx_k_set_all_openmodes), 0, 1, 1},
  {&__pyx_kp_get_openmodes, __pyx_k_get_openmodes, sizeof(__pyx_k_get_openmodes), 0, 1, 1},
  {&__pyx_kp_set_some_openmodes, __pyx_k_set_some_openmodes, sizeof(__pyx_k_set_some_openmodes), 0, 1, 1},
  {&__pyx_kp_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 1, 1},
  {&__pyx_kp_async, __pyx_k_async, sizeof(__pyx_k_async), 0, 1, 1},
  {&__pyx_kp_mod_owner, __pyx_k_mod_owner, sizeof(__pyx_k_mod_owner), 0, 1, 1},
  {&__pyx_kp_get_owner, __pyx_k_get_owner, sizeof(__pyx_k_get_owner), 0, 1, 1},
  {&__pyx_kp_select, __pyx_k_select, sizeof(__pyx_k_select), 0, 1, 1},
  {&__pyx_kp_2, __pyx_k_2, sizeof(__pyx_k_2), 0, 0, 0},
  {&__pyx_kp_mach_port, __pyx_k_mach_port, sizeof(__pyx_k_mach_port), 1, 1, 1},
  {0, 0, 0, 0, 0}
};

static PyObject *__pyx_tp_new_6pyhurd_4hurd_IO(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = __pyx_ptype_6pyhurd_4mach_MachPort->tp_new(t, a, k);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_6pyhurd_4hurd_IO(PyObject *o) {
  __pyx_ptype_6pyhurd_4mach_MachPort->tp_dealloc(o);
}

static struct PyMethodDef __pyx_methods_6pyhurd_4hurd_IO[] = {
  {"__str__", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO___str__, METH_NOARGS|METH_COEXIST, 0},
  {"readable", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_readable, METH_NOARGS, __pyx_doc_6pyhurd_4hurd_2IO_readable},
  {"read", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_read, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6pyhurd_4hurd_2IO_read},
  {"write", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_write, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6pyhurd_4hurd_2IO_write},
  {"seek", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_seek, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6pyhurd_4hurd_2IO_seek},
  {"set_all_openmodes", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_set_all_openmodes, METH_O, __pyx_doc_6pyhurd_4hurd_2IO_set_all_openmodes},
  {"get_openmodes", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_get_openmodes, METH_NOARGS, __pyx_doc_6pyhurd_4hurd_2IO_get_openmodes},
  {"set_some_openmodes", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_set_some_openmodes, METH_O, __pyx_doc_6pyhurd_4hurd_2IO_set_some_openmodes},
  {"clear_some_openmodes", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_clear_some_openmodes, METH_O, __pyx_doc_6pyhurd_4hurd_2IO_clear_some_openmodes},
  {"async", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_async, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6pyhurd_4hurd_2IO_async},
  {"mod_owner", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_mod_owner, METH_O, __pyx_doc_6pyhurd_4hurd_2IO_mod_owner},
  {"get_owner", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_get_owner, METH_NOARGS, __pyx_doc_6pyhurd_4hurd_2IO_get_owner},
  {"select", (PyCFunction)__pyx_pf_6pyhurd_4hurd_2IO_select, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6pyhurd_4hurd_2IO_select},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_6pyhurd_4hurd_IO[] = {
  {"io_object", T_UINT, offsetof(struct __pyx_obj_6pyhurd_4hurd_IO, io_object), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_IO = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_divide*/
  #endif
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_coerce*/
  #endif
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_oct*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*nb_hex*/
  #endif
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_inplace_divide*/
  #endif
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX)
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_IO = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_IO = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_IO = {
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getreadbuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getwritebuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getsegcount*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getcharbuffer*/
  #endif
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_NEWBUFFER)
  0, /*bf_getbuffer*/
  #endif
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_NEWBUFFER)
  0, /*bf_releasebuffer*/
  #endif
};

PyTypeObject __pyx_type_6pyhurd_4hurd_IO = {
  PyVarObject_HEAD_INIT(0, 0)
  "pyhurd.hurd.IO", /*tp_name*/
  sizeof(struct __pyx_obj_6pyhurd_4hurd_IO), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_6pyhurd_4hurd_IO, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_IO, /*tp_as_number*/
  &__pyx_tp_as_sequence_IO, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_IO, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  __pyx_pf_6pyhurd_4hurd_2IO___str__, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_IO, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_6pyhurd_4hurd_IO, /*tp_methods*/
  __pyx_members_6pyhurd_4hurd_IO, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_6pyhurd_4hurd_IO, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC inithurd(void); /*proto*/
PyMODINIT_FUNC inithurd(void) {
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("hurd", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  __pyx_int_0 = PyInt_FromLong(0); if (unlikely(!__pyx_int_0)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;};
  __pyx_int_1 = PyInt_FromLong(1); if (unlikely(!__pyx_int_1)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_ptype_6pyhurd_4mach_MachPort = __Pyx_ImportType("pyhurd.mach", "MachPort", sizeof(struct __pyx_obj_6pyhurd_4mach_MachPort)); if (unlikely(!__pyx_ptype_6pyhurd_4mach_MachPort)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 4; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_type_6pyhurd_4hurd_IO.tp_base = __pyx_ptype_6pyhurd_4mach_MachPort;
  if (PyType_Ready(&__pyx_type_6pyhurd_4hurd_IO) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "IO", (PyObject *)&__pyx_type_6pyhurd_4hurd_IO) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 20; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_6pyhurd_4hurd_IO = &__pyx_type_6pyhurd_4hurd_IO;
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/home/jimcrow/pyhurd/pyhurd/io.pyx":203
 *         return error, owner
 * 
 *     def select (self, reply, timeout, select_type):             # <<<<<<<<<<<<<<
 *         """
 *         SELECT_TYPE is the bitwise OR of SELECT_READ, SELECT_WRITE, and SELECT_URG.
 */
  return;
  __pyx_L1:;
  __Pyx_AddTraceback("pyhurd.hurd");
}

static const char *__pyx_filenames[] = {
  "io.pyx",
  "pyhurd.hurd.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(module_name);
    #else
    py_name = PyUnicode_FromString(module_name);
    #endif
    if (!py_name)
        goto bad;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    result = PyObject_GetAttrString(py_module, class_name);
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_name);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
