/* Generated by Cython 0.9.6.12 on Sun May 18 21:32:51 2008 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#ifndef WIN32
  #define __stdcall
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "gnu_source.h"
#include "stdlib.h"
#include "hurd.h"
#include "fcntl.h"
#include "hurd/io.h"
#include "stdio.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s;} __Pyx_InternTabEntry; /*proto*/
typedef struct {PyObject **p; char *s; long n; int is_unicode;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static char __pyx_mdoc[] = "\nPyHurd - A pytonish GNU/Hurd\n";

static int __Pyx_CheckKeywordStrings(PyObject *kwdict, const char* function_name, int kw_allowed); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from pyhurd */

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":12
 * O_TRUNC = _O_TRUNC
 * 
 * cdef class IO:             # <<<<<<<<<<<<<< 
 *     cdef readonly mach_port_t io_object
 *     
 */

struct __pyx_obj_6pyhurd_IO {
  PyObject_HEAD
  mach_port_t io_object;
};


static PyTypeObject *__pyx_ptype_6pyhurd_IO = 0;


/* Implementation of pyhurd */


static PyObject *__pyx_num_0;

static PyObject *__pyx_n___cinit__;
static PyObject *__pyx_n___dealloc__;
static PyObject *__pyx_n___str__;
static PyObject *__pyx_n_readable;
static PyObject *__pyx_n_read;
static PyObject *__pyx_n_write;
static PyObject *__pyx_n_seek;
static PyObject *__pyx_n_O_READ;
static PyObject *__pyx_n_O_WRITE;
static PyObject *__pyx_n_O_CREAT;
static PyObject *__pyx_n_O_TRUNC;
static PyObject *__pyx_n_MACH_PORT_NULL;

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":15
 *     cdef readonly mach_port_t io_object
 *     
 *     def __new__ (self):             # <<<<<<<<<<<<<< 
 *         self.io_object = _MACH_PORT_NULL
 * 
 */

static int __pyx_pf_6pyhurd_2IO___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_6pyhurd_2IO___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  if (unlikely(PyTuple_GET_SIZE(__pyx_args) > 0)) {
    PyErr_Format(PyExc_TypeError, "function takes at most %d positional arguments (%d given)", 0, PyTuple_GET_SIZE(__pyx_args));
    return -1;
  }
  if (unlikely(__pyx_kwds)) {
    if (unlikely(!__Pyx_CheckKeywordStrings(__pyx_kwds, "__new__", 0))) return -1;
  }
  Py_INCREF(__pyx_v_self);

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":16
 *     
 *     def __new__ (self):
 *         self.io_object = _MACH_PORT_NULL             # <<<<<<<<<<<<<< 
 * 
 *     def __dealloc__ (self):
 */
  ((struct __pyx_obj_6pyhurd_IO *)__pyx_v_self)->io_object = MACH_PORT_NULL;

  __pyx_r = 0;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":18
 *         self.io_object = _MACH_PORT_NULL
 * 
 *     def __dealloc__ (self):             # <<<<<<<<<<<<<< 
 *         mach_port_deallocate(mach_task_self(), self.io_object)
 * 
 */

static void __pyx_pf_6pyhurd_2IO___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_pf_6pyhurd_2IO___dealloc__(PyObject *__pyx_v_self) {
  Py_INCREF(__pyx_v_self);

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":19
 * 
 *     def __dealloc__ (self):
 *         mach_port_deallocate(mach_task_self(), self.io_object)             # <<<<<<<<<<<<<< 
 * 
 *     def __str__ (self):
 */
  mach_port_deallocate(mach_task_self(), ((struct __pyx_obj_6pyhurd_IO *)__pyx_v_self)->io_object);

  Py_DECREF(__pyx_v_self);
}

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":21
 *         mach_port_deallocate(mach_task_self(), self.io_object)
 * 
 *     def __str__ (self):             # <<<<<<<<<<<<<< 
 *         return 'IO: mach port: %s' % self.io_object
 * 
 */

static PyObject *__pyx_k_1p;

static char __pyx_k_1[] = "IO: mach port: %s";

static PyObject *__pyx_pf_6pyhurd_2IO___str__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_6pyhurd_2IO___str__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":22
 * 
 *     def __str__ (self):
 *         return 'IO: mach port: %s' % self.io_object             # <<<<<<<<<<<<<< 
 * 
 *     def readable (self):
 */
  __pyx_1 = PyLong_FromUnsignedLong(((struct __pyx_obj_6pyhurd_IO *)__pyx_v_self)->io_object); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  __pyx_2 = PyNumber_Remainder(__pyx_k_1p, __pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 22; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.IO.__str__");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":24
 *         return 'IO: mach port: %s' % self.io_object
 * 
 *     def readable (self):             # <<<<<<<<<<<<<< 
 *         """
 *         Checks if io object is readable and return avaiable amount
 */

static PyObject *__pyx_pf_6pyhurd_2IO_readable(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static char __pyx_doc_6pyhurd_2IO_readable[] = "\n        Checks if io object is readable and return avaiable amount\n        of data to read/write\n\n        Return:\n            tuple of error and amount integer values\n\n        Hurd definition:\n            kern_return_t io_readable (\n                io_t io_object,\n                vm_size_t *amount)\n        ";
static PyObject *__pyx_pf_6pyhurd_2IO_readable(PyObject *__pyx_v_self, PyObject *unused) {
  vm_size_t __pyx_v_amount;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":38
 *         """
 * 
 *         cdef vm_size_t amount = 0             # <<<<<<<<<<<<<< 
 *         error = io_readable(self.io_object, &amount)
 * 
 */
  __pyx_v_amount = 0;


  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":39
 * 
 *         cdef vm_size_t amount = 0
 *         error = io_readable(self.io_object, &amount)             # <<<<<<<<<<<<<< 
 * 
 *         return error, amount
 */
  __pyx_1 = PyInt_FromLong(io_readable(((struct __pyx_obj_6pyhurd_IO *)__pyx_v_self)->io_object, (&__pyx_v_amount))); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_1;
  __pyx_1 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":41
 *         error = io_readable(self.io_object, &amount)
 * 
 *         return error, amount             # <<<<<<<<<<<<<< 
 * 
 *     def read (self, amount, offset = 0):
 */
  __pyx_1 = PyLong_FromUnsignedLong(__pyx_v_amount); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("pyhurd.IO.readable");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":43
 *         return error, amount
 * 
 *     def read (self, amount, offset = 0):             # <<<<<<<<<<<<<< 
 *         """
 *         Reads data from io object.
 */

static PyObject *__pyx_num_1;

static PyObject *__pyx_pf_6pyhurd_2IO_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6pyhurd_2IO_read[] = "\n        Reads data from io object.\n\n        Parameters:\n            offset\n            amount\n\n        Returns:\n            tuple of error (integer) and data (string)\n            None - if nothing to read\n\n        Hurd definition:\n            kern_return_t io_read (\n                io_t io_object,\n                data_t *data,\n                mach_msg_type_number_t *dataCnt,\n                loff_t offset,\n                vm_size_t amount)\n        ";
static PyObject *__pyx_pf_6pyhurd_2IO_read(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_amount = 0;
  PyObject *__pyx_v_offset = 0;
  vm_size_t __pyx_v_read_amount;
  data_t __pyx_v_data;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  size_t __pyx_2;
  loff_t __pyx_3;
  vm_size_t __pyx_4;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"amount","offset",0};
  __pyx_v_offset = __pyx_num_0;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    __pyx_v_amount = PyTuple_GET_ITEM(__pyx_args, 0);
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_offset = PyTuple_GET_ITEM(__pyx_args, 1);
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_amount, &__pyx_v_offset))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  return NULL;
  __pyx_L3:;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_amount);
  Py_INCREF(__pyx_v_offset);
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":65
 * 
 *         cdef vm_size_t read_amount
 *         cdef data_t data = <data_t>malloc(amount + 1)             # <<<<<<<<<<<<<< 
 *         error = io_read(self.io_object, &data, &read_amount, offset, amount)
 * 
 */
  __pyx_1 = PyNumber_Add(__pyx_v_amount, __pyx_num_1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  __pyx_2 = PyInt_AsUnsignedLongMask(__pyx_1); if (unlikely((__pyx_2 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_v_data = ((char *)malloc(__pyx_2));


  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":66
 *         cdef vm_size_t read_amount
 *         cdef data_t data = <data_t>malloc(amount + 1)
 *         error = io_read(self.io_object, &data, &read_amount, offset, amount)             # <<<<<<<<<<<<<< 
 * 
 *         if read_amount == 0:
 */
  __pyx_3 = __pyx_PyInt_long(__pyx_v_offset); if (unlikely((__pyx_3 == (long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  __pyx_4 = PyInt_AsUnsignedLongMask(__pyx_v_amount); if (unlikely((__pyx_4 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  __pyx_1 = PyInt_FromLong(io_read(((struct __pyx_obj_6pyhurd_IO *)__pyx_v_self)->io_object, (&__pyx_v_data), (&__pyx_v_read_amount), __pyx_3, __pyx_4)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_1;
  __pyx_1 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":68
 *         error = io_read(self.io_object, &data, &read_amount, offset, amount)
 * 
 *         if read_amount == 0:             # <<<<<<<<<<<<<< 
 *             return None
 * 
 */
  __pyx_5 = (__pyx_v_read_amount == 0);
  if (__pyx_5) {

    /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":69
 * 
 *         if read_amount == 0:
 *             return None             # <<<<<<<<<<<<<< 
 * 
 *         data[read_amount] = c'\0'
 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":71
 *             return None
 * 
 *         data[read_amount] = c'\0'             # <<<<<<<<<<<<<< 
 *         return error, data
 * 
 */
  (__pyx_v_data[__pyx_v_read_amount]) = '\0';

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":72
 * 
 *         data[read_amount] = c'\0'
 *         return error, data             # <<<<<<<<<<<<<< 
 * 
 *     def write (self, data, offset = 0):
 */
  __pyx_1 = PyString_FromString(__pyx_v_data); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  __pyx_6 = PyTuple_New(2); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_6, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_6, 1, __pyx_1);
  __pyx_1 = 0;
  __pyx_r = __pyx_6;
  __pyx_6 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("pyhurd.IO.read");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_amount);
  Py_DECREF(__pyx_v_offset);
  return __pyx_r;
}

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":74
 *         return error, data
 * 
 *     def write (self, data, offset = 0):             # <<<<<<<<<<<<<< 
 *         """
 *         Writes data to io object.
 */

static PyObject *__pyx_pf_6pyhurd_2IO_write(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6pyhurd_2IO_write[] = "\n        Writes data to io object.\n\n        Parameters:\n            data - string to write\n            offset\n\n        Returns:\n          tuple of error and amount values\n\n        Hurd definition:\n            kern_return_t io_write (\n                io_t io_object,\n	        data_t data,\n	        mach_msg_type_number,\n	        loff_t offset,\n	        vm_size_t *amount)\n        ";
static PyObject *__pyx_pf_6pyhurd_2IO_write(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_data = 0;
  PyObject *__pyx_v_offset = 0;
  vm_size_t __pyx_v_write_amount;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  data_t __pyx_1;
  Py_ssize_t __pyx_2 = 0;
  loff_t __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"data","offset",0};
  __pyx_v_offset = __pyx_num_0;
  if (likely(!__pyx_kwds) && likely(1 <= PyTuple_GET_SIZE(__pyx_args)) && likely(PyTuple_GET_SIZE(__pyx_args) <= 2)) {
    __pyx_v_data = PyTuple_GET_ITEM(__pyx_args, 0);
    if (PyTuple_GET_SIZE(__pyx_args) > 1) {
      __pyx_v_offset = PyTuple_GET_ITEM(__pyx_args, 1);
    }
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O|O", __pyx_argnames, &__pyx_v_data, &__pyx_v_offset))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 74; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  return NULL;
  __pyx_L3:;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_data);
  Py_INCREF(__pyx_v_offset);
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":95
 * 
 *         cdef vm_size_t write_amount
 *         error = io_write(self.io_object, data, len(data), offset, &write_amount)             # <<<<<<<<<<<<<< 
 *         return error, write_amount
 * 
 */
  __pyx_1 = PyString_AsString(__pyx_v_data); if (unlikely((!__pyx_1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_2 = PyObject_Length(__pyx_v_data); if (unlikely(__pyx_2 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_3 = __pyx_PyInt_long(__pyx_v_offset); if (unlikely((__pyx_3 == (long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  __pyx_4 = PyInt_FromLong(io_write(((struct __pyx_obj_6pyhurd_IO *)__pyx_v_self)->io_object, __pyx_1, __pyx_2, __pyx_3, (&__pyx_v_write_amount))); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_4;
  __pyx_4 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":96
 *         cdef vm_size_t write_amount
 *         error = io_write(self.io_object, data, len(data), offset, &write_amount)
 *         return error, write_amount             # <<<<<<<<<<<<<< 
 * 
 *     def seek (self, offset, whence):
 */
  __pyx_4 = PyLong_FromUnsignedLong(__pyx_v_write_amount); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  __pyx_5 = PyTuple_New(2); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 96; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_5, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
  __pyx_4 = 0;
  __pyx_r = __pyx_5;
  __pyx_5 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("pyhurd.IO.write");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_data);
  Py_DECREF(__pyx_v_offset);
  return __pyx_r;
}

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":98
 *         return error, write_amount
 * 
 *     def seek (self, offset, whence):             # <<<<<<<<<<<<<< 
 *         """
 *         Change current read/write offset
 */

static PyObject *__pyx_pf_6pyhurd_2IO_seek(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_6pyhurd_2IO_seek[] = "\n        Change current read/write offset\n\n        Return:\n            tuple of error and new position\n\n        Hurd definition:\n            kern_return_t io_seek (\n                io_t io_object,\n                loff_t offset,\n                int whence,\n                loff_t * newp)\n        ";
static PyObject *__pyx_pf_6pyhurd_2IO_seek(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_offset = 0;
  PyObject *__pyx_v_whence = 0;
  loff_t __pyx_v_new_position;
  PyObject *__pyx_v_error;
  PyObject *__pyx_r;
  loff_t __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"offset","whence",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_offset = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_whence = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_offset, &__pyx_v_whence))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  return NULL;
  __pyx_L3:;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_offset);
  Py_INCREF(__pyx_v_whence);
  __pyx_v_error = Py_None; Py_INCREF(Py_None);

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":114
 * 
 *         cdef loff_t new_position
 *         error = io_seek(self.io_object, offset, whence, &new_position)             # <<<<<<<<<<<<<< 
 *         return error, new_position
 */
  __pyx_1 = __pyx_PyInt_long(__pyx_v_offset); if (unlikely((__pyx_1 == (long)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_whence); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(io_seek(((struct __pyx_obj_6pyhurd_IO *)__pyx_v_self)->io_object, __pyx_1, __pyx_2, (&__pyx_v_new_position))); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 114; goto __pyx_L1;}
  Py_DECREF(__pyx_v_error);
  __pyx_v_error = __pyx_3;
  __pyx_3 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":115
 *         cdef loff_t new_position
 *         error = io_seek(self.io_object, offset, whence, &new_position)
 *         return error, new_position             # <<<<<<<<<<<<<< 
 */
  __pyx_3 = PyInt_FromLong(__pyx_v_new_position); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; goto __pyx_L1;}
  Py_INCREF(__pyx_v_error);
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_v_error);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_3 = 0;
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("pyhurd.IO.seek");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_error);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_offset);
  Py_DECREF(__pyx_v_whence);
  return __pyx_r;
}

/* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/glibc.pyx":6
 * include "glibc.pxi"
 * 
 * def file_name_lookup(filename, flags, mode):             # <<<<<<<<<<<<<< 
 *     io_object = glibc_file_name_lookup(filename, flags, mode)
 * 
 */

static PyObject *__pyx_pf_6pyhurd_file_name_lookup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_6pyhurd_file_name_lookup(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_filename = 0;
  PyObject *__pyx_v_flags = 0;
  PyObject *__pyx_v_mode = 0;
  PyObject *__pyx_v_io_object;
  struct __pyx_obj_6pyhurd_IO *__pyx_v_io = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  int __pyx_2;
  mode_t __pyx_3;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  int __pyx_6;
  mach_port_t __pyx_7;
  static char *__pyx_argnames[] = {"filename","flags","mode",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 3)) {
    __pyx_v_filename = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_flags = PyTuple_GET_ITEM(__pyx_args, 1);
    __pyx_v_mode = PyTuple_GET_ITEM(__pyx_args, 2);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOO", __pyx_argnames, &__pyx_v_filename, &__pyx_v_flags, &__pyx_v_mode))) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 6; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  return NULL;
  __pyx_L3:;
  Py_INCREF(__pyx_v_filename);
  Py_INCREF(__pyx_v_flags);
  Py_INCREF(__pyx_v_mode);
  __pyx_v_io_object = Py_None; Py_INCREF(Py_None);

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/glibc.pyx":7
 * 
 * def file_name_lookup(filename, flags, mode):
 *     io_object = glibc_file_name_lookup(filename, flags, mode)             # <<<<<<<<<<<<<< 
 * 
 *     if io_object == _MACH_PORT_NULL:
 */
  __pyx_1 = PyString_AsString(__pyx_v_filename); if (unlikely((!__pyx_1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_flags); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_3 = __pyx_PyInt_unsigned_short(__pyx_v_mode); if (unlikely((__pyx_3 == (unsigned short)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 7; goto __pyx_L1;}
  __pyx_4 = PyLong_FromUnsignedLong(file_name_lookup(__pyx_1, __pyx_2, __pyx_3)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_v_io_object);
  __pyx_v_io_object = __pyx_4;
  __pyx_4 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/glibc.pyx":9
 *     io_object = glibc_file_name_lookup(filename, flags, mode)
 * 
 *     if io_object == _MACH_PORT_NULL:             # <<<<<<<<<<<<<< 
 *         return None
 * 
 */
  __pyx_4 = PyInt_FromLong(MACH_PORT_NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 9; goto __pyx_L1;}
  __pyx_5 = PyObject_RichCompare(__pyx_v_io_object, __pyx_4, Py_EQ); if (unlikely(!__pyx_5)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_6 = __Pyx_PyObject_IsTrue(__pyx_5); if (unlikely(__pyx_6 < 0)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_5); __pyx_5 = 0;
  if (__pyx_6) {

    /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/glibc.pyx":10
 * 
 *     if io_object == _MACH_PORT_NULL:
 *         return None             # <<<<<<<<<<<<<< 
 * 
 *     cdef IO io = IO()
 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/glibc.pyx":12
 *         return None
 * 
 *     cdef IO io = IO()             # <<<<<<<<<<<<<< 
 *     io.io_object = io_object
 * 
 */
  __pyx_4 = PyObject_Call(((PyObject*)__pyx_ptype_6pyhurd_IO), __pyx_empty_tuple, NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 12; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_4, __pyx_ptype_6pyhurd_IO)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 12; goto __pyx_L1;}
  __pyx_v_io = ((struct __pyx_obj_6pyhurd_IO *)__pyx_4);
  __pyx_4 = 0;


  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/glibc.pyx":13
 * 
 *     cdef IO io = IO()
 *     io.io_object = io_object             # <<<<<<<<<<<<<< 
 * 
 *     return io */
  __pyx_7 = PyInt_AsUnsignedLongMask(__pyx_v_io_object); if (unlikely((__pyx_7 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 13; goto __pyx_L1;}
  __pyx_v_io->io_object = __pyx_7;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/glibc.pyx":15
 *     io.io_object = io_object
 * 
 *     return io             # <<<<<<<<<<<<<< 
 */
  Py_INCREF(((PyObject *)__pyx_v_io));
  __pyx_r = ((PyObject *)__pyx_v_io);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("pyhurd.file_name_lookup");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_io_object);
  Py_XDECREF(__pyx_v_io);
  Py_DECREF(__pyx_v_filename);
  Py_DECREF(__pyx_v_flags);
  Py_DECREF(__pyx_v_mode);
  return __pyx_r;
}

static __Pyx_InternTabEntry __pyx_intern_tab[] = {
  {&__pyx_n_MACH_PORT_NULL, "MACH_PORT_NULL"},
  {&__pyx_n_O_CREAT, "O_CREAT"},
  {&__pyx_n_O_READ, "O_READ"},
  {&__pyx_n_O_TRUNC, "O_TRUNC"},
  {&__pyx_n_O_WRITE, "O_WRITE"},
  {&__pyx_n___cinit__, "__cinit__"},
  {&__pyx_n___dealloc__, "__dealloc__"},
  {&__pyx_n___str__, "__str__"},
  {&__pyx_n_read, "read"},
  {&__pyx_n_readable, "readable"},
  {&__pyx_n_seek, "seek"},
  {&__pyx_n_write, "write"},
  {0, 0}
};

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_k_1p, __pyx_k_1, sizeof(__pyx_k_1), 0},
  {0, 0, 0, 0}
};

static PyObject *__pyx_tp_new_6pyhurd_IO(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  if (__pyx_pf_6pyhurd_2IO___new__(o, __pyx_empty_tuple, NULL) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_6pyhurd_IO(PyObject *o) {
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_pf_6pyhurd_2IO___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_6pyhurd_IO[] = {
  {"__str__", (PyCFunction)__pyx_pf_6pyhurd_2IO___str__, METH_NOARGS|METH_COEXIST, 0},
  {"readable", (PyCFunction)__pyx_pf_6pyhurd_2IO_readable, METH_NOARGS, __pyx_doc_6pyhurd_2IO_readable},
  {"read", (PyCFunction)__pyx_pf_6pyhurd_2IO_read, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6pyhurd_2IO_read},
  {"write", (PyCFunction)__pyx_pf_6pyhurd_2IO_write, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6pyhurd_2IO_write},
  {"seek", (PyCFunction)__pyx_pf_6pyhurd_2IO_seek, METH_VARARGS|METH_KEYWORDS, __pyx_doc_6pyhurd_2IO_seek},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_6pyhurd_IO[] = {
  {"io_object", T_UINT, offsetof(struct __pyx_obj_6pyhurd_IO, io_object), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_IO = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_IO = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_IO = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_IO = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_6pyhurd_IO = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "pyhurd.IO", /*tp_name*/
  sizeof(struct __pyx_obj_6pyhurd_IO), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_6pyhurd_IO, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_IO, /*tp_as_number*/
  &__pyx_tp_as_sequence_IO, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_IO, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  __pyx_pf_6pyhurd_2IO___str__, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_IO, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_6pyhurd_IO, /*tp_methods*/
  __pyx_members_6pyhurd_IO, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_6pyhurd_IO, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"file_name_lookup", (PyCFunction)__pyx_pf_6pyhurd_file_name_lookup, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initpyhurd(void); /*proto*/
PyMODINIT_FUNC initpyhurd(void) {
  PyObject *__pyx_1 = 0;
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("pyhurd", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 4; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 4; goto __pyx_L1;};
  /*--- Intern code ---*/
  __pyx_num_0 = PyInt_FromLong(0); if (unlikely(!__pyx_num_0)) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 4; goto __pyx_L1;};
  __pyx_num_1 = PyInt_FromLong(1); if (unlikely(!__pyx_num_1)) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 4; goto __pyx_L1;};
  if (__Pyx_InternStrings(__pyx_intern_tab) < 0) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 4; goto __pyx_L1;};
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 4; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 4; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Function import code ---*/
  /*--- Type init code ---*/
  if (PyType_Ready(&__pyx_type_6pyhurd_IO) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "IO", (PyObject *)&__pyx_type_6pyhurd_IO) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; goto __pyx_L1;}
  __pyx_ptype_6pyhurd_IO = &__pyx_type_6pyhurd_IO;
  /*--- Type import code ---*/
  /*--- Execution code ---*/

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":7
 * include "io.pxi"
 * 
 * O_READ = _O_READ             # <<<<<<<<<<<<<< 
 * O_WRITE = _O_WRITE
 * O_CREAT = _O_CREAT
 */
  __pyx_1 = PyInt_FromLong(O_READ); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_O_READ, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 7; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":8
 * 
 * O_READ = _O_READ
 * O_WRITE = _O_WRITE             # <<<<<<<<<<<<<< 
 * O_CREAT = _O_CREAT
 * O_TRUNC = _O_TRUNC
 */
  __pyx_1 = PyInt_FromLong(O_WRITE); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_O_WRITE, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 8; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":9
 * O_READ = _O_READ
 * O_WRITE = _O_WRITE
 * O_CREAT = _O_CREAT             # <<<<<<<<<<<<<< 
 * O_TRUNC = _O_TRUNC
 * 
 */
  __pyx_1 = PyInt_FromLong(O_CREAT); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_O_CREAT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 9; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/io.pyx":10
 * O_WRITE = _O_WRITE
 * O_CREAT = _O_CREAT
 * O_TRUNC = _O_TRUNC             # <<<<<<<<<<<<<< 
 * 
 * cdef class IO:
 */
  __pyx_1 = PyInt_FromLong(O_TRUNC); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_O_TRUNC, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 10; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/arne/Dokumente/eigenes/Programme/Hurd/pyhurd/pyhurd/pyhurd.pyx":17
 * include "glibc.pyx"
 * 
 * MACH_PORT_NULL = None             # <<<<<<<<<<<<<< 
 * 
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_n_MACH_PORT_NULL, Py_None) < 0) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 17; goto __pyx_L1;}
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("pyhurd");
}

static char *__pyx_filenames[] = {
  "io.pyx",
  "glibc.pyx",
  "pyhurd.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_CheckKeywordStrings(
    PyObject *kwdict,
    const char* function_name,
    int kw_allowed)
{
    PyObject* key = 0;
    Py_ssize_t pos = 0;
    while (PyDict_Next(kwdict, &pos, &key, 0)) {
        if (unlikely(!PyString_Check(key))) {
            PyErr_Format(PyExc_TypeError,
                         "%s() keywords must be strings", function_name);
            return 0;
        }
    }
    if (unlikely(!kw_allowed) && unlikely(key)) {
        PyErr_Format(PyExc_TypeError,
                     "'%s' is an invalid keyword argument for this function",
                     PyString_AsString(key));
        return 0;
    }
    return 1;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static int __Pyx_InternStrings(__Pyx_InternTabEntry *t) {
    while (t->p) {
        *t->p = PyString_InternFromString(t->s);
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
